name: Mise à jour de la version de Supabase

on:
  push:
    branches:
      - master

jobs:
  update_metabase_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🛠️ Installation de la CLI Scalingo
        uses: scalingo-community/setup-scalingo@87fe86eedc708ffb9d232c756b21f6a5784f6c8a # v0.1.1
        with:
          #  Jeton personnel.
          api_token: ${{ secrets.SCALINGO_API_TOKEN }}
          region: 'osc-fr1'

      - name: mise à jour de METABASE_VERSION
        run: |
          METABASE_VERSION=$(sed -n 's#^FROM metabase/metabase:\(v.*\)$#\1#p' < docker/Dockerfile)
          if [[ ! -n "$METABASE_VERSION" ]]; then
            exit 0
          fi

          CURRENT_METABASE_VERSION=$(scalingo --app docurba-metabase env-get METABASE_VERSION)
          if [[ "$METABASE_VERSION" > "$CURRENT_METABASE_VERSION" ]]; then
            echo Upgrading Metabase from "$CURRENT_METABASE_VERSION" to "$METABASE_VERSION"
            scalingo --app docurba-metabase env-set METABASE_VERSION="$METABASE_VERSION"
            scalingo --app docurba-metabase restart
          fi
